### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by norkunas** [dunglas/DunglasAngularCsrfBundle#16]
This bundle does handle the csrf when authenticating with ajax request.

**Comment by dunglas** [comment]
What do you mean? When using the `form_login` system of Symfony?

**Comment by norkunas** [comment]
Yes, is it possible to set a csrf provider for login form as this bundle?

**Comment by dunglas** [comment]
I've not tested it but as the bundle Symfony events it should be possible.
