### ISSUE TITLE
"expire" option in configuration doesn't work

### ISSUE THREAD

**Issue by nmarniesse** [dunglas/DunglasAngularCsrfBundle#17]
Actually the expire option is used to set a fix time (unix time) in the cookie. In my opinion it would be better to set an expiration time depending actual time

AngularCsrfCookieListener.php :

        $event->getResponse()->headers->setCookie(new Cookie(
            $this->cookieName,
            $this->angularCsrfTokenManager->getToken()->getValue(),
            time() + $this->cookieExpire,
            $this->cookiePath,
            $this->cookieDomain,
            $this->cookieSecure,
            false
        ));

By the way thanks for your bundle :)

**Comment by henne001** [comment]
Hi,

One small remark on this change: setting the cookie expire option to '0' (or not setting the option at all), now invalidates the cookie immediately after it is issued. 'time() + $this->cookieExpire' -> 'time() + 0'. 

In the 'Full configuration' example on the main page this is the case. Perhaps some additional comment in the documentation could make it clear that setting '0' is a no-go, as it is confusing in comparison to the default PHP behaviour regarding cookie lifetimes.

(source: http://www.w3schools.com/php/func_http_setcookie.asp)
_Specifies when the cookie expires. The value: time()+86400*30, will set the cookie to expire in 30 days. If this parameter is omitted or set to 0, the cookie will expire at the end of the session (when the browser closes). Default is 0_
