### ISSUE TITLE
CSRF Protection fails for framework-intercepted actions

### ISSUE THREAD

**Issue by Uriziel** [dunglas/DunglasAngularCsrfBundle#18]
CSRF Protection will fail for actions like login unless higher priority is set on listener.
https://github.com/dunglas/DunglasAngularCsrfBundle/blob/master/Resources/config/services.xml#L29

**Comment by dunglas** [comment]
Good catch! Can you open a PR?

**Comment by Uriziel** [comment]
Fixed.
