### ISSUE TITLE
Tag a New Version?

### ISSUE THREAD

**Issue by chrisguitarguy** [dunglas/DunglasAngularCsrfBundle#22]
0.1 was tagged in January 2014. There's a lot of new features in master. Can we get a new tag so users don't have to use `dev-master` in their composer.json?

**Comment by PurpleYellow** [comment]
+1

**Comment by dunglas** [comment]
Done: https://github.com/dunglas/DunglasAngularCsrfBundle/releases/tag/v1.0.0
