### ISSUE TITLE
Error in DependencyInjection Configuration

### ISSUE THREAD

**Issue by st0at** [dunglas/DunglasAngularCsrfBundle#26]
Hi,
When I enable the bundle in Symfony 3 application, I get error in dependency injection configuration:
[Symfony\Component\Config\Definition\Exception\InvalidDefinitionException]  
  ->cannotBeEmpty() is not applicable to NumericNodeDefinition.               

Exception trace:
 () at .../vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Builder/NumericNodeDefinition.php:71
 Symfony\Component\Config\Definition\Builder\NumericNodeDefinition->cannotBeEmpty() at .../vendor/dunglas/angular-csrf-bundle/DependencyInjection/Configuration.php:49
 Dunglas\AngularCsrfBundle\DependencyInjection\Configuration->getConfigTreeBuilder() at .../vendor/symfony/symfony/src/Symfony/Component/Config/Definition/Processor.php:50
 Symfony\Component\Config\Definition\Processor->processConfiguration() at .../vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Extension/Extension.php:105
 Symfony\Component\DependencyInjection\Extension\Extension->processConfiguration() at .../vendor/dunglas/angular-csrf-bundle/DependencyInjection/DunglasAngularCsrfExtension.php:32

**Comment by tomaszozga** [comment]
+1

**Comment by kejwmen** [comment]
already fixed:
https://github.com/dunglas/DunglasAngularCsrfBundle/commit/e5e7afa96e0441e2af4d44ede15855dbf3161b1a#diff-850942b3ba24ab03a40aaa81b6152852L49

**Comment by dunglas** [comment]
I'm working on a new release including this patch.

**Comment by rickerd** [comment]
@dunglas the 1.x version still has the error. I need to checkout dev-master for able it to work.
(SF 3.x)

**Comment by dunglas** [comment]
Yes, I need to tag a new version.

**Comment by dunglas** [comment]
New version tagged.
