### ISSUE TITLE
Exclude certain routes

### ISSUE THREAD

**Issue by rickerd** [dunglas/DunglasAngularCsrfBundle#30]
I want to exclude a certain route(s).
Mollie needs to connect to my API and put a payment to a certain status.

Is this possible? I really need an answer for it.

Thanks in advance.

**Comment by fatganz** [comment]
Tried to solve that with #40

**Comment by leevigraham** [comment]
Released in https://github.com/dunglas/DunglasAngularCsrfBundle/releases/tag/v1.2.0 @dunglas This can be closed.
