### ISSUE TITLE
Missing 

### ISSUE THREAD

**Issue by tarjei** [dunglas/DunglasAngularCsrfBundle#32]
Hi, after I upgraded to Symfony 2.7 the Form-extension stopped working. To get it to work again, I had to change the tag definition of `dunglas_angular_csrf.form.extension.disable_csrf` 
from 

```
<tag name="form.type_extension" alias="form"/>
```

```
<tag name="form.type_extension" alias="form" extended-type="Symfony\Component\Form\Extension\Core\Type\FormType" />
```

Also I had to change the returnvalue of getExtendedType from `form` to `FormType::class`

I think the changes needed require Symfony 2.7 but I'm not quite sure.

**Comment by AlexandreKilian** [comment]
I had the same problem, but actually this was fixed in https://github.com/dunglas/DunglasAngularCsrfBundle/commit/e5e7afa96e0441e2af4d44ede15855dbf3161b1a , just didn't make it into master yet apparently...

**Comment by AlexandreKilian** [comment]
Actually, no, the dev-master version fixed the cookie-checking, but the cookie isn't getting set

**Comment by AlexandreKilian** [comment]
I have a solution to stay on v1.0 (the working branch) and integrate this fix without having to override the service in the vendors (since I'm deploying with capifony, I don't have that "luxury").
I wrote a Custom Compiler Pass, that overrides the tag and fixes it:

```
 <?php
namespace AppBundle\DependencyInjection\Compiler;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class OverrideServiceCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
      if (!$container->hasDefinition('dunglas_angular_csrf.form.extension.disable_csrf')) {
           return;
       }
        $definition = $container->getDefinition('dunglas_angular_csrf.form.extension.disable_csrf');

        $tags = $definition->getTags();

        $tags['form.type_extension'][0]['extended-type'] = "Symfony\Component\Form\Extension\Core\Type\FormType";
        $tags['form.type_extension'][0]['extended_type'] = "Symfony\Component\Form\Extension\Core\Type\FormType";
        $definition->setTags($tags);
        $container->setDefinition('dunglas_angular_csrf.form.extension.disable_csrf', $definition);

    }
}

```

**Comment by dunglas** [comment]
Fixed in the last release.
