### ISSUE TITLE
1.0.0 Has a Bug with Cookie Expiration Time

### ISSUE THREAD

**Issue by chrisguitarguy** [dunglas/DunglasAngularCsrfBundle#35]
Fixed in this commit: 5479263a0aa78221d2350d52eb51d747e0ea7d33

Would it be possible to get a tagged patch version with the fix?

**Comment by tenitski** [comment]
This commit breaks default behaviour (expiry being set to 0)

**Comment by chrisguitarguy** [comment]
1.0.1 was released, thanks @dunglas !
