### ISSUE TITLE
Config for security.yml

### ISSUE THREAD

**Issue by dineety** [dunglas/DunglasAngularCsrfBundle#36]
Hello,

I install the bundle but i don't know how i configure /app/config/security.yml

My file :

`security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
                id: fos_user.user_provider.username

    firewalls:

        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
        logout: true
        anonymous: true

    access_control:
            - { path: ^/api, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin/, role: ROLE_ADMIN }`

Thanks for your help

**Comment by dineety** [comment]
I find the solution, in the README, there's an error 

`# app/config/security.yml

dunglas_angular_csrf:
    # Collection of patterns where to set the cookie
    cookie:
        set_on:
            - { path: ^/$ }
            - { route: ^app_, methods: [GET, HEAD] }
            - { host: example.com }
    # Collection of patterns to secure
    secure:
        - { path: ^/api, methods: [POST, PUT, PATCH, LINK] }
        - { route: ^api_v2_ }
        - { host: example.com, methods: [POST, PUT, PATCH, LINk] }`

It's in # app/config/config.yml

**Comment by dunglas** [comment]
IIRC, you can put this config in any of those 2 files.
