### ISSUE TITLE
Form CSRF Token Disiabling No Longer Works in Symfony 3.2

### ISSUE THREAD

**Issue by chrisguitarguy** [dunglas/DunglasAngularCsrfBundle#39]
Looks like its due to a change in the order type extensions are loaded. See https://github.com/symfony/symfony/pull/19790.

The form type extension in this bundle loads before the core csrf extension. So a valid csrf token from this bundle disable csrf protection on a form, only to have it enabled again by the core csrf extension.

I'm not sure if this is a BC break in symfony itself, or something that's a bug (ish, Symfony changing underneath you is not really a bug) in this bundle.

**Comment by dmaicher** [comment]
Should have been fixed by https://github.com/symfony/symfony/pull/20995
