### ISSUE TITLE
Symfony fails to load if CsrfTokenManager is not loaded

### ISSUE THREAD

**Issue by nesl247** [dunglas/DunglasAngularCsrfBundle#45]
`The service "form.registry" has a dependency on a non-existent service "dunglas_angular_csrf.form.extension.disable_csrf"` is the error I get. I am working on upgrading an existing 3.3 app to the symfony/flex architecture.

The issue is caused by the fact that the `CsrfCompilerPass` removes the service if `CsrfTokenManager` doesn't exist. However, it does not remove the extension from Twig.

**Comment by dunglas** [comment]
@nesl247 it's fixed in #44. However I struggle to find the time to finish this PR... Some help to make the remaining tests green would be very appreciated.
