### ISSUE TITLE
Please make dunglas_angular_csrf.token_manager service public

### ISSUE THREAD

**Issue by danaki** [dunglas/DunglasAngularCsrfBundle#55]
I'm trying to make your bundle work for GraphiQL interface following [documentation](https://github.com/overblog/GraphiQLBundle/blob/master/Resources/doc/custom-http-headers.md)

Because dunglas_angular_csrf.token_manager is set to public=false I'm using the following workaround:
```
<?php

namespace App\Twig;

use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\Security\Csrf\CsrfTokenManagerInterface;

class GraphiQLCSRFExtension extends \Twig_Extension
{
    /**
     * @var CsrfTokenManagerInterface
     */
    protected $csrfTokenManager;

    protected $tokenId;

    /**
     * Constructor.
     *
     * @param CsrfTokenManagerInterface $csrfTokenManager
     */
    public function __construct(CsrfTokenManagerInterface $csrfTokenManager, ContainerInterface $container)
    {
        $this->csrfTokenManager = $csrfTokenManager;
        $this->tokenId = $container->getParameter('dunglas_angular_csrf.token.id');
    }

    public function getFunctions()
    {
        return [
            new \Twig_Function('getCSRFToken', function () {
                return $this->csrfTokenManager->getToken($this->tokenId);
            }),
        ];
    }
}
```

It would be great if my code didn't know about dunglas_angular_csrf.token.id parameter but use the configured service.

**Comment by robinvdvleuten** [comment]
Yes please! I do not use CSRF cookies, but an endpoint instead to generate CSRF tokens.

**Comment by dunglas** [comment]
This service shouldn't be public, what we must do is to create an alias (id = FQN) to allow to inject it using the autowiring.

**Comment by robinvdvleuten** [comment]
That would be even better! I can create a PR for that if you like, @dunglas?
