### ISSUE TITLE
Trouble in testing

### ISSUE THREAD

**Issue by nschurmann** [dunglas/DunglasAngularCsrfBundle#7]
Hello,

Great bundle, but i'm having issues with the testing, it changes the value of the csrf token at the second instance, seems that doesn't recognise the session id. Could you give some pointers on how to make tests when using this bundle?

regards!

**Comment by dunglas** [comment]
What strategy (or tool) do you use for testing?
The CSRF token is stored in a cookie, does your testing tool support cookies?

**Comment by nschurmann** [comment]
I'm using phpunit, following this http://symfony.com/doc/current/book/testing.html

Here is the code, but it will ask for another csrf token on the post.

https://gist.github.com/nschurmann/fdec6899665fa3ee925f

**Comment by dunglas** [comment]
The HTTP header must be `X-XSRF-TOKEN`. In your code its `HTTP_X_XSRF_TOKEN`. Does it work if you change that?

**Comment by nschurmann** [comment]
not really, that is a must to set headers in symfony2 tests. So the header in the request is actually `x-xsrf-token`

Do you have a tutorial or guide in how to write tests with your bundle?

**Comment by dunglas** [comment]
@nschurmann No I haven't. I personally successfully use Behat for that kind of tests.
Can you for the Symfony Standard Edition and add some example and a failing test to give me the ability to hack it?

**Comment by nschurmann** [comment]
@dunglas NVM, was a problem with a configuration, i had enabled the CSRF protection in the form. Disabling it allowed to use your bundle configuration instead of symfony's.

**Comment by dunglas** [comment]
:+1:

**Comment by dunglas** [comment]
Need to fix #6

**Comment by leevigraham** [comment]
@dunglas Quick question regarding Behat testing. 

I'm having issues with token storage not recognising an existing token. I can see in the Symfony profiler that the x-xsrf-token is being sent in the request.

Stepping through the code CsrfTokenManager::isTokenValid() is failing on the $this->storage->hasToken($token->getId()) check.

I'm using `session.storage.filesystem` session storage and it looks like 2 .mocksess files are being created for my feature.

    a:3:{s:15:"_sf2_attributes";a:0:{}s:12:"_sf2_flashes";a:0:{}s:9:"_sf2_meta";a:3:{s:1:"u";i:1443839362;s:1:"c";i:1443839362;s:1:"l";s:1:"0";}}

    a:3:{s:15:"_sf2_attributes";a:0:{}s:12:"_sf2_flashes";a:0:{}s:9:"_sf2_meta";a:3:{s:1:"u";i:1443839363;s:1:"c";i:1443839363;s:1:"l";s:1:"0";}}

Here's my feature:

    Scenario: Post JSON
      Given I am authenticating with jwt token as "user1" with "password" password
      And I have a valid csrf header
      And I set header "Accept" with value "application/json"
      And I send a POST request to "/api/1/projects" with body:
      """
      {
          "project": {
              "title": "boardworld.com.au v2",
              "workspace": 1
          }
      }
      """
      Then the response code should be 201

Any ideas why the session token storage is not being set correctly?

**Comment by leevigraham** [comment]
@dunglas I think I figured it out. I was using the https://github.com/Behat/WebApiExtension to test the endpoints which was using a Guzzle client. The session storage when first setting the token and then session storage when doing the request are different.

**Comment by dunglas** [comment]
Great. Can you add mention about that in the doc? I'm sure it can help other people.

**Comment by leevigraham** [comment]
@dunglas Sure… When I figure out the full solution :)
