### ISSUE TITLE
Bad csrf token

### ISSUE THREAD

**Issue by fatmah** [dunglas/DunglasAngularCsrfBundle#8]
Hello,
I 'm having "bad csrf token",  in my request header there is nothing about XSRF-TOKEN.
I just installed the bundle with the configuration in the doc and I disabled the csrf protection in the  formType.Did I miss anything please??? 
Regards!

**Comment by dunglas** [comment]
Is the cookie cookie correctly set (`set_on` config key)? Which version of Symfony and AngularJS are you using?

**Comment by fatmah** [comment]
set_on:
          - { path: ^/$ }
          - { route: ^app_, methods: [GET, HEAD] }
and I am using symfony 2.6, angular ~1.2.23 , restangular~1.3.1

**Comment by dunglas** [comment]
Can you check (using Chrome's Web Developper tools) that a cookie called `XSRF-TOKEN` is set?

**Comment by fatmah** [comment]
no it does'nt exist

**Comment by fatmah** [comment]
POST /app_dev.php/farmers HTTP/1.1
Host: cmsang
Connection: keep-alive
Content-Length: 82
Accept: application/json, text/plain, */*
Origin: http://cmsang
User-Agent: Mozilla/5.0 (X11; Linux i686) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.114 Safari/537.36
Content-Type: application/json;charset=UTF-8
Referer: http://cmsang/app_dev.php/front/farmer
Accept-Encoding: gzip,deflate,sdch
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4
Cookie: PHPSESSID=j7bnnrs3nll0hivj86mppa0257

**Comment by dunglas** [comment]
So that's the problem. Double check your configuration. Can you copy/paster here the return of `app/console router:debug` please?

**Comment by fatmah** [comment]
[router] Current routes
 Name                              Method   Scheme Host Path                                  
 _welcome                          ANY      ANY    ANY  /                                     
 _wdt                              ANY      ANY    ANY  /_wdt/{token}                         
 _profiler_home                    ANY      ANY    ANY  /_profiler/                           
 _profiler_search                  ANY      ANY    ANY  /_profiler/search                     
 _profiler_search_bar              ANY      ANY    ANY  /_profiler/search_bar                 
 _profiler_purge                   ANY      ANY    ANY  /_profiler/purge                      
 _profiler_info                    ANY      ANY    ANY  /_profiler/info/{about}               
 _profiler_phpinfo                 ANY      ANY    ANY  /_profiler/phpinfo                    
 _profiler_search_results          ANY      ANY    ANY  /_profiler/{token}/search/results     
 _profiler                         ANY      ANY    ANY  /_profiler/{token}                    
 _profiler_router                  ANY      ANY    ANY  /_profiler/{token}/router             
 _profiler_exception               ANY      ANY    ANY  /_profiler/{token}/exception          
 _profiler_exception_css           ANY      ANY    ANY  /_profiler/{token}/exception.css      
 _configurator_home                ANY      ANY    ANY  /_configurator/                       
 _configurator_step                ANY      ANY    ANY  /_configurator/step/{index}           
 _configurator_final               ANY      ANY    ANY  /_configurator/final                  
 application_user_default_index    ANY      ANY    ANY  /hello/{name}                         
 new_complaint                     GET      ANY    ANY  /complaints/new.{_format}             
 edit_complaints                   GET      ANY    ANY  /complaints/{id}/edit.{_format}       
 remove_complaints                 GET      ANY    ANY  /complaints/{id}/remove.{_format}     
 get_complaints                    GET      ANY    ANY  /complaints.{_format}                 
 get_complaint                     GET      ANY    ANY  /complaints/{id}.{_format}            
 post_complaints                   POST     ANY    ANY  /complaints.{_format}                 
 put_complaints                    PUT      ANY    ANY  /complaints/{id}.{_format}            
 delete_complaints                 DELETE   ANY    ANY  /complaints/{id}.{_format}            
 get_farmers                       GET      ANY    ANY  /farmers.{_format}                    
 get_farmer                        GET      ANY    ANY  /farmers/{id}.{_format}               
 post_farmers                      POST     ANY    ANY  /farmers.{_format}                    
 put_farmer                        PUT      ANY    ANY  /farmers/{id}.{_format}               
 delete_farmer                     DELETE   ANY    ANY  /farmers/{id}.{_format}               
 new_direction                     GET      ANY    ANY  /directions/new.{_format}             
 edit_directions                   GET      ANY    ANY  /directions/{id}/edit.{_format}       
 remove_directions                 GET      ANY    ANY  /directions/{id}/remove.{_format}     
 get_directions                    GET      ANY    ANY  /directions.{_format}                 
 get_direction                     GET      ANY    ANY  /directions/{id}.{_format}            
 post_directions                   POST     ANY    ANY  /directions.{_format}                 
 put_directions                    PUT      ANY    ANY  /directions/{id}.{_format}            
 delete_directions                 DELETE   ANY    ANY  /directions/{id}.{_format}            
 new_workflow                      GET      ANY    ANY  /workflows/new.{_format}              
 edit_workflows                    GET      ANY    ANY  /workflows/{id}/edit.{_format}        
 remove_workflows                  GET      ANY    ANY  /workflows/{id}/remove.{_format}      
 get_workflows                     GET      ANY    ANY  /workflows.{_format}                  
 get_workflow                      GET      ANY    ANY  /workflows/{id}.{_format}             
 post_workflows                    POST     ANY    ANY  /workflows.{_format}                  
 put_workflows                     PUT      ANY    ANY  /workflows/{id}.{_format}             
 delete_workflows                  DELETE   ANY    ANY  /workflows/{id}.{_format}             
 new_typecomplaint                 GET      ANY    ANY  /typecomplaints/new.{_format}         
 edit_typecomplaints               GET      ANY    ANY  /typecomplaints/{id}/edit.{_format}   
 remove_typecomplaints             GET      ANY    ANY  /typecomplaints/{id}/remove.{_format} 
 get_typecomplaints                GET      ANY    ANY  /typecomplaints.{_format}             
 get_typecomplaint                 GET      ANY    ANY  /typecomplaints/{id}.{_format}        
 post_typecomplaints               POST     ANY    ANY  /typecomplaints.{_format}             
 put_typecomplaints                PUT      ANY    ANY  /typecomplaints/{id}.{_format}        
 delete_typecomplaints             DELETE   ANY    ANY  /typecomplaints/{id}.{_format}        
 new_group                         GET      ANY    ANY  /groups/new.{_format}                 
 edit_groups                       GET      ANY    ANY  /groups/{id}/edit.{_format}           
 remove_groups                     GET      ANY    ANY  /groups/{id}/remove.{_format}         
 get_groups                        GET      ANY    ANY  /groups.{_format}                     
 get_group                         GET      ANY    ANY  /groups/{id}.{_format}                
 post_groups                       POST     ANY    ANY  /groups.{_format}                     
 put_groups                        PUT      ANY    ANY  /groups/{id}.{_format}                
 delete_groups                     DELETE   ANY    ANY  /groups/{id}.{_format}                
 new_todo                          GET      ANY    ANY  /todos/new.{_format}                  
 edit_todos                        GET      ANY    ANY  /todos/{id}/edit.{_format}            
 remove_todos                      GET      ANY    ANY  /todos/{id}/remove.{_format}          
 get_todos                         GET      ANY    ANY  /todos.{_format}                      
 get_todo                          GET      ANY    ANY  /todos/{id}.{_format}                 
 post_todos                        POST     ANY    ANY  /todos.{_format}                      
 put_todos                         PUT      ANY    ANY  /todos/{id}.{_format}                 
 delete_todos                      DELETE   ANY    ANY  /todos/{id}.{_format}                 
 _front                            ANY      ANY    ANY  /TodoMVC                              
 _front_cms_farmer                 ANY      ANY    ANY  /front/farmer                         
 _front_cms_complaint              ANY      ANY    ANY  /front/complaint                      
 _front_cms_workflow               ANY      ANY    ANY  /front/workflow                       
 nelmio_api_doc_index              GET      ANY    ANY  /api/doc/                             
 fos_user_security_login           ANY      ANY    ANY  /login                                
 fos_user_security_check           POST     ANY    ANY  /login_check                          
 fos_user_security_logout          ANY      ANY    ANY  /logout                               
 fos_user_profile_show             GET      ANY    ANY  /profile/                             
 fos_user_profile_edit             ANY      ANY    ANY  /profile/edit                         
 fos_user_registration_register    ANY      ANY    ANY  /register/                            
 fos_user_registration_check_email GET      ANY    ANY  /register/check-email                 
 fos_user_registration_confirm     GET      ANY    ANY  /register/confirm/{token}             
 fos_user_registration_confirmed   GET      ANY    ANY  /register/confirmed                   
 fos_user_resetting_request        GET      ANY    ANY  /resetting/request                    
 fos_user_resetting_send_email     POST     ANY    ANY  /resetting/send-email                 
 fos_user_resetting_check_email    GET      ANY    ANY  /resetting/check-email                
 fos_user_resetting_reset          GET|POST ANY    ANY  /resetting/reset/{token}              
 fos_user_change_password          GET|POST ANY    ANY  /profile/change-password              
 fos_user_group_list               GET      ANY    ANY  /group/list                           
 fos_user_group_new                ANY      ANY    ANY  /group/new                            
 fos_user_group_show               GET      ANY    ANY  /group/{groupname}                    
 fos_user_group_edit               ANY      ANY    ANY  /group/{groupname}/edit               
 fos_user_group_delete             GET      ANY    ANY  /group/{groupname}/delete             
 new_user                          GET      ANY    ANY  /users/new.{_format}                  
 edit_users                        GET      ANY    ANY  /users/{id}/edit.{_format}            
 remove_users                      GET      ANY    ANY  /users/{id}/remove.{_format}          
 get_users                         GET      ANY    ANY  /users.{_format}                      
 get_user                          GET      ANY    ANY  /users/{id}.{_format}                 
 post_users                        POST     ANY    ANY  /users.{_format}                      
 put_users                         PUT      ANY    ANY  /users/{id}.{_format}                 
 delete_users                      DELETE   ANY    ANY  /users/{id}.{_format}                 
 bazinga_jstranslation_js          GET      ANY    ANY  /translations/{domain}.{_format}

**Comment by dunglas** [comment]
You must look for the cookie on the first request (the `/` page).

The process is:
* go to `/` (the cookie must be set)
* let the Angular request the API (`/farmers` - the header should be sent by Angular if the cookie has been correctly set)

**Comment by fatmah** [comment]
Thank you it works :) but this mean that i should add all form routes in the set_on ?

**Comment by dunglas** [comment]
All entry points of the application (from where the Angular code is served).

**Comment by fatmah** [comment]
I 'm confused I 'm not sure that it did work , I can't get it working again the XSRF-TOKEN cookie is on the response header not the request : Set-Cookie:XSRF-TOKEN=893_AZYONdqPTMGioHbN0umCGf5cSaAHfGHMkyAX5as; expires=Fri, 02-Jan-1970 03:46:40 GMT; Max-Age=-1421569798; path=/; domain=cmsang

**Comment by dunglas** [comment]
It's intended.

**Comment by fatmah** [comment]
but i still having the bad csrf token exception

**Comment by dunglas** [comment]
The cookie must be set on the HTTP response serving the Angular call. All next calls must include a header (set by Angular) with the value of the cookie.

**Comment by fatmah** [comment]
thank you Dunglas now it's clear it works!  :)

**Comment by nsarvar** [comment]
Hi! I've facing the same issue and cannot fix it. Here's my config: 

```
dunglas_angular_csrf:
    cookie:
        set_on:
            - { path: ^/$ }
            - { route: ^app_, methods: [GET, HEAD,] }
    secure:
        - { path: ^/api, methods: [DELETE, POST, PUT, PATCH, LINK] }
        - { route: ^api_v2_ }
```

When I click the button on angular4 app, it sends the request: 
```
delete(id: number): Observable<any> {
    let headers = new Headers({ 'Content-Type': 'application/json',
      'Accept': 'q=0.8;application/json;q=0.9' });
    let options = new RequestOptions({ headers: this.headers });

    return this.http
      .delete(this.apiUri + '/apartment/' + id, options)
      .map(this.extractData)
      .catch(this.handleError);
  }
```
This is request and response in  headers: 

![image](https://user-images.githubusercontent.com/7187733/30240557-b0271200-956a-11e7-94c9-3dd7977f73e2.png)

**Comment by dunglas** [comment]
You need to set the `X-XSRF-TOKEN` token yourself in JavaScript. It's precisely what protect from CSRF attacks. The value of the header must be the token available in the `XSRF-TOKEN` cookie.

**Comment by nsarvar** [comment]
I tried to get XSRF-TOKEN value using Angular, but it couldn't read the Set-Cookie on header. In the documentation, it says we cannot get access to read it. If found withCredentials: true option which returns the XSRF-TOKEN back without modification. Now, it seems working, but I still get Bad CSRF token error. 
Here's a screenshot: 
![image](https://user-images.githubusercontent.com/7187733/30245136-4e2f1efe-95c8-11e7-804a-f9fb554c57d6.png)

**Comment by dunglas** [comment]
What you need to do is:

* read the cookie `XSRF-Token` value
* Set a new `X-XSRF-Token` header, use the token retrieved from the cookie as value (it's missing in your example)

It was done automatically by Angular 1 but it's not the case Angular since Angular 2.

**Comment by nsarvar** [comment]
Finely, issue is solved, cannot believe I spent 2 days on it and thank you so much for support. 
Just want to make some comment for my code so it might be helpful to someone in the future. 
When sessioid response came from the server, it is written on client cookie automatically. I just read the cookie, and created new header `X-XSRF-Token` as you said:

`const tokenReq = req.clone({
      headers: req.headers.set('X-XSRF-TOKEN', this.cookieService.get('XSRF-TOKEN'))
    });
`
In the above code, intercept is using which is new feature in Angular 4.3

**Comment by dunglas** [comment]
Would you mind opening a PR to add this to the README?

**Comment by nsarvar** [comment]
I have added integration with Angular 4.3 in the README, but isn't showed up on the main README.

**Comment by dunglas** [comment]
Do you have opened the PR? There is nothing in the list: https://github.com/dunglas/DunglasAngularCsrfBundle/pulls

**Comment by nsarvar** [comment]
ah, sorry you mean Pull Request. I misunderstood, I'll do it later.

**Comment by nsarvar** [comment]
I've edited README directly and saved
